### ISSUE TITLE
Can we make line height more than 20?

### ISSUE THREAD

**Issue by AlexALX** [AzeTheGreat/ONI-Mods#21]
https://github.com/AzeTheGreat/ONI-Mods/blob/957cbed9b3b00882e8c9f1e772819b9b0a28edd7/src/BetterInfoCards/Util/Options.cs#L40

Hi, i just curious, can we make this limit up to 30 for example? It seems like 20 is way much low for me to make comfortable look. Is there any other limit in files besides this line?

**Comment by AzeTheGreat** [comment]
@AlexALX: yes, this is doable.  Do you need the icons to increase in size as well?  Or is the vanilla sizing for those fine.

**Comment by AlexALX** [comment]
For better customizing i guess yes can make bigger limit for those who needs this.

**Comment by AzeTheGreat** [comment]
This is fixed with b162837ebfb13a080c70d68b5c2627eb9daea1dd.  Instead of overriding minimum height, my option now directly sets the spacing between text lines.  This has effectively doubled the configurable line spacing.

Release e824be2233cd87b33c2e948a227462f08cf0eb28 includes other related improvements: fix a vanilla spacing bug, improve BIC options screen, and increasable icon sizes.
