### ISSUE TITLE
Better Automation Overlay crash after update

### ISSUE THREAD

**Issue by zivvel** [AzeTheGreat/ONI-Mods#22]
Update this morning sounds awesome.

Crashed when I hit shift+F2.

[Player.log](https://github.com/AzeTheGreat/ONI-Mods/files/9794326/Player.log)

**Comment by zivvel** [comment]
Also, I am running public_previous_update branch.

**Comment by AzeTheGreat** [comment]
@zivvel: Thanks for the report.  That's an annoying side effect: the update added an overload instead of implicitly casting a parameter, so that overload is missing from the old version's assemblies.

Since this is an outdated branch issue, I will consider this a non-issue.  You can manually install the previous version of the mod [here](https://github.com/AzeTheGreat/ONI-Mods/blob/f8299afde2afb72f1626cb4481c682bb80a7846f/Distribute/BetterLogicOverlay.zip) or update to the current branch.

**Comment by zivvel** [comment]
> @zivvel: Thanks for the report. That's an annoying side effect: the update added an overload instead of implicitly casting a parameter, so that overload is missing from the old version's assemblies.
> 
> Since this is an outdated branch issue, I will consider this a non-issue. You can manually install the previous version of the mod [here](https://github.com/AzeTheGreat/ONI-Mods/blob/f8299afde2afb72f1626cb4481c682bb80a7846f/Distribute/BetterLogicOverlay.zip) or update to the current branch.

Thanks.  I actually went ahead to the current ONI branch after filing my report, and everything is peachy after updating Fast Track.
