### ISSUE TITLE
Default Save Settings+Default Building Settings - Translation

### ISSUE THREAD

**Issue by DarkEviL88** [AzeTheGreat/ONI-Mods#41]
Default Save Settings - Ru
I made a translation of the mod, but the settings menu is still in English.
[ru.zip](https://github.com/AzeTheGreat/ONI-Mods/files/14354044/ru.zip)

**Comment by DarkEviL88** [comment]
Default Building Settings - Ru
[ru.zip](https://github.com/AzeTheGreat/ONI-Mods/files/14354121/ru.zip)

**Comment by AzeTheGreat** [comment]
Thanks for the contributions!  I do have a question: what process are you using to create these?  POEdit, manual editing, something else?

I ask because I'm seeing some weird formatting and I'm not sure where it's coming from.

Template
![image](https://github.com/AzeTheGreat/ONI-Mods/assets/36392269/910a77a1-54ec-40ee-ae6d-0e66752e87f8)
Translation
![image](https://github.com/AzeTheGreat/ONI-Mods/assets/36392269/60f10000-b60f-48b8-a32a-6d2b1e1844d0)

**Comment by DarkEviL88** [comment]
This is the program I use to create translations from templates:
![image](https://github.com/AzeTheGreat/ONI-Mods/assets/50534207/61b4728c-70fe-48ed-82b7-01e4317cc000)

**Comment by DarkEviL88** [comment]
I think it happens when I enclose some text in quotes instead of using an apostrophe, although in your screenshot, I used «».
When I do the translation and try to experiment.

**Comment by DarkEviL88** [comment]
Нет, это происходит не из-за знаков, такое впечатление будто строка сильно длинная и программа переносит слова таким образом. Та же самая проблема и с файлом перевода infinite research.

**Comment by DarkEviL88** [comment]
![image](https://github.com/AzeTheGreat/ONI-Mods/assets/50534207/b0039505-8ae3-42d7-a37f-5e202bcc22cf)

**Comment by DarkEviL88** [comment]
But when I corrected the text with notepad++, when I resave it with poedit, this weird formatting doesn't happen.

**Comment by AzeTheGreat** [comment]
Interesting.  I was able to reproduce the POEdit issue.  Doesn't seem to affect anything so I suppose it's not an issue.

Translations added in d88c63b3c15fec25d3a3afd60c20d68f0f244a05 and c1b63b02166174519aa1913413c62dfd1b92b3ca.  Both should be available on Steam.
